--
-- PostgreSQL database dump
--

\restrict JyNIUjs4KnSW4PrsBbxeS4ryEZXGZOg837CsaqPt8F6dgLEx1VKCV6HlMaYuoTA

-- Dumped from database version 14.19 (Homebrew)
-- Dumped by pg_dump version 14.19 (Homebrew)

-- Started on 2026-01-14 16:51:57 CET

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 838 (class 1247 OID 16535)
-- Name: ruolo_enum; Type: TYPE; Schema: public; Owner: postgres
--

CREATE TYPE public.ruolo_enum AS ENUM (
    'ADMIN',
    'MEDICO',
    'PAZIENTE'
);


ALTER TYPE public.ruolo_enum OWNER TO postgres;

--
-- TOC entry 841 (class 1247 OID 16553)
-- Name: stato_approvazione_enum; Type: TYPE; Schema: public; Owner: postgres
--

CREATE TYPE public.stato_approvazione_enum AS ENUM (
    'PENDING',
    'APPROVATO',
    'RIFIUTATO'
);


ALTER TYPE public.stato_approvazione_enum OWNER TO postgres;

--
-- TOC entry 853 (class 1247 OID 16598)
-- Name: stato_prenotazione_enum; Type: TYPE; Schema: public; Owner: postgres
--

CREATE TYPE public.stato_prenotazione_enum AS ENUM (
    'RICHIESTA',
    'CONFERMATA',
    'RIFIUTATA',
    'COMPLETATA'
);


ALTER TYPE public.stato_prenotazione_enum OWNER TO postgres;

--
-- TOC entry 865 (class 1247 OID 16682)
-- Name: tipo_metrica_enum; Type: TYPE; Schema: public; Owner: postgres
--

CREATE TYPE public.tipo_metrica_enum AS ENUM (
    'PESO',
    'PRESSIONE_MAX',
    'PRESSIONE_MIN',
    'GLICEMIA'
);


ALTER TYPE public.tipo_metrica_enum OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 214 (class 1259 OID 16579)
-- Name: dettagli_medici; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.dettagli_medici (
    id bigint NOT NULL,
    utente_id bigint NOT NULL,
    specializzazione_id integer NOT NULL,
    numero_albo character varying(50) NOT NULL,
    biografia text,
    indirizzo_studio character varying(255),
    stato_approvazione public.stato_approvazione_enum DEFAULT 'PENDING'::public.stato_approvazione_enum
);


ALTER TABLE public.dettagli_medici OWNER TO postgres;

--
-- TOC entry 213 (class 1259 OID 16578)
-- Name: dettagli_medici_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.dettagli_medici ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dettagli_medici_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 16756)
-- Name: impostazioni_notifiche; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.impostazioni_notifiche (
    utente_id bigint NOT NULL,
    notifiche_email boolean DEFAULT true
);


ALTER TABLE public.impostazioni_notifiche OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 16729)
-- Name: messaggi; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.messaggi (
    id bigint NOT NULL,
    mittente_id bigint NOT NULL,
    destinatario_id bigint NOT NULL,
    testo text NOT NULL,
    letto boolean DEFAULT false,
    data_invio timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.messaggi OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 16728)
-- Name: messaggi_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.messaggi ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.messaggi_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 16692)
-- Name: metriche_salute; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.metriche_salute (
    id bigint NOT NULL,
    paziente_id bigint NOT NULL,
    medico_id bigint NOT NULL,
    tipo public.tipo_metrica_enum NOT NULL,
    valore numeric(5,2) NOT NULL,
    unita_misura character varying(20),
    data_misurazione date DEFAULT CURRENT_DATE
);


ALTER TABLE public.metriche_salute OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 16691)
-- Name: metriche_salute_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.metriche_salute ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.metriche_salute_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 216 (class 1259 OID 16627)
-- Name: prenotazioni; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.prenotazioni (
    id bigint NOT NULL,
    paziente_id bigint NOT NULL,
    medico_id bigint NOT NULL,
    data_visita timestamp without time zone NOT NULL,
    stato public.stato_prenotazione_enum DEFAULT 'RICHIESTA'::public.stato_prenotazione_enum,
    motivo text
);


ALTER TABLE public.prenotazioni OWNER TO postgres;

--
-- TOC entry 215 (class 1259 OID 16626)
-- Name: prenotazioni_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.prenotazioni ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.prenotazioni_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 16670)
-- Name: prescrizioni; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.prescrizioni (
    id bigint NOT NULL,
    visita_id bigint NOT NULL,
    nome_farmaco character varying(150) NOT NULL,
    dosaggio character varying(150),
    data_emissione date DEFAULT CURRENT_DATE,
    data_fine date NOT NULL
);


ALTER TABLE public.prescrizioni OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16669)
-- Name: prescrizioni_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.prescrizioni ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.prescrizioni_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 212 (class 1259 OID 16571)
-- Name: specializzazioni; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.specializzazioni (
    id bigint NOT NULL,
    nome character varying(100) NOT NULL
);


ALTER TABLE public.specializzazioni OWNER TO postgres;

--
-- TOC entry 211 (class 1259 OID 16570)
-- Name: specializzazioni_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.specializzazioni ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.specializzazioni_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 210 (class 1259 OID 16560)
-- Name: utenti; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.utenti (
    id bigint NOT NULL,
    email character varying(100) NOT NULL,
    password character varying(255) NOT NULL,
    nome character varying(100) NOT NULL,
    cognome character varying(100) NOT NULL,
    telefono character varying(20),
    data_nascita date,
    ruolo public.ruolo_enum NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    sesso character varying(1)
);


ALTER TABLE public.utenti OWNER TO postgres;

--
-- TOC entry 209 (class 1259 OID 16559)
-- Name: utenti_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.utenti ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.utenti_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 16646)
-- Name: visite; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.visite (
    id bigint NOT NULL,
    prenotazione_id bigint,
    paziente_id bigint NOT NULL,
    medico_id bigint NOT NULL,
    diagnosi text,
    note_medico text,
    data_visita timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.visite OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 16645)
-- Name: visite_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.visite ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.visite_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3874 (class 0 OID 16579)
-- Dependencies: 214
-- Data for Name: dettagli_medici; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.dettagli_medici (id, utente_id, specializzazione_id, numero_albo, biografia, indirizzo_studio, stato_approvazione) FROM stdin;
4	5	7	ALBO-CT-004	Medico specializzato in ginecologia e ostetricia	Via Plebiscito, 10, 95121 Catania CT	PENDING
1	2	1	ALBO-RM-001	Specialista in cardiologia, esperto in ipertensione.	Via Roma, 10, 00060 Formello RM	APPROVATO
2	3	2	ALBO-MI-002	Dermatologa specializzata in medicina estetica.	Corso Italia, 25, 20122 Milano MI	APPROVATO
3	4	4	ALBO-TO-003	Ortopedico traumatologo, specializzato in chirurgia del ginocchio.	Via Po, 18, 10123 Torino TO	APPROVATO
\.


--
-- TOC entry 3885 (class 0 OID 16756)
-- Dependencies: 225
-- Data for Name: impostazioni_notifiche; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.impostazioni_notifiche (utente_id, notifiche_email) FROM stdin;
2	t
3	t
4	t
5	t
6	t
7	t
8	t
9	t
10	t
\.


--
-- TOC entry 3884 (class 0 OID 16729)
-- Dependencies: 224
-- Data for Name: messaggi; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.messaggi (id, mittente_id, destinatario_id, testo, letto, data_invio) FROM stdin;
1	2	6	Grazie per avermi scelto, per qualsiasi dubbio sono a sua completa disposizione!	t	2026-01-13 16:04:36.234463
2	8	2	Buongiorno Dottore, ultimamente sento un leggero dolore al petto quando faccio le scale. Devo preoccuparmi?	t	2025-12-20 10:57:04.662655
3	2	8	Buongiorno Roberto. Data l'età e i sintomi, è meglio non sottovalutare. Prenota una visita per un ECG e un controllo generale il prima possibile.	t	2025-12-21 10:57:04.662655
4	8	2	Dottore, ho iniziato la cura. Il Bisoprololo devo prenderlo a stomaco pieno o vuoto?	t	2025-12-27 10:57:04.673253
5	2	8	È indifferente, l'importante è che lo prenda sempre alla stessa ora, preferibilmente al mattino.	t	2025-12-27 12:57:04.673253
6	8	2	Sto monitorando la pressione come richiesto. Stamattina era 125/80, mi sembra molto meglio rispetto all'ultima volta.	t	2026-01-03 10:57:04.691904
7	2	8	Ottimo Roberto. I valori stanno rientrando nella norma. Vediamoci domani per la visita di controllo e confermare la terapia.	t	2026-01-03 14:57:04.691904
8	8	2	Dottore, mi scusi il disturbo. La ricetta per il Bisoprololo è ripetibile o devo passare in studio per il rinnovo?	t	2026-01-14 09:57:04.700971
9	2	8	Buongiorno Roberto, quando vuole può passare in studio per il rinnovo.	f	2026-01-14 11:58:12.001563
10	7	3	Buongiorno Dottoressa, ho un problema di acne che sta peggiorando. Posso prenotare una visita?	t	2025-11-05 11:03:53.867871
11	3	7	Certamente Giulia, prenota pure tramite l'apposita sezione. Ti aspetto.	t	2025-11-06 11:03:53.867871
12	7	3	Dottoressa, il gel mi brucia molto e la pelle si squama. È normale?	t	2025-11-30 11:03:53.867871
13	3	7	Sì, è un effetto retinoide atteso. Prova a metterlo a sere alterne e usa molta crema idratante al mattino.	t	2025-11-30 13:03:53.867871
14	7	3	Buonasera, le confermo che sarò presente all'appuntamento del 19 Gennaio. La pelle va molto meglio!	f	2026-01-14 09:03:53.867871
15	6	2	Buongiorno Dottore, per la visita di martedì 13 devo portare gli ultimi esami del sangue anche se sono di 6 mesi fa?	t	2026-01-10 09:30:00
16	2	6	Sì Luca, porti tutto quello che ha. Ci vediamo in studio.	t	2026-01-10 10:15:00
17	6	2	Buongiorno, vedo che il referto non è ancora online. Quando pensa di riuscire a caricarlo?	f	2026-01-14 10:13:27.741093
18	10	2	Dottore, ho spesso forti mal di testa al risveglio. Potrebbe essere la pressione?	t	2025-12-01 08:30:00
19	2	10	È molto probabile Paolo. Vieni subito in studio che la misuriamo.	t	2025-12-01 09:15:00
20	10	2	Dottore, la pillola mi fa girare un po' la testa quando mi alzo. È normale?	t	2025-12-10 14:00:00
21	2	10	Sì, all'inizio può succedere. Cerca di alzarti lentamente. Se persiste ne parliamo al controllo del 20.	t	2025-12-10 15:20:00
22	10	2	Buongiorno, sto prendendo il dosaggio da 20mg e va molto meglio. Ci vediamo il 29 come d'accordo.	f	2026-01-14 09:17:08.995151
23	9	2	Buonasera Dottore, ultimamente ho il cuore che batte fortissimo anche quando sono seduta sul divano. Mi devo preoccupare?	t	2025-12-10 18:30:00
24	2	9	Ciao Anna, potrebbe essere un po' di stress ma meglio controllare. Vieni venerdì che facciamo un tracciato.	t	2025-12-10 19:15:00
25	9	2	Dottore, ho preso la pillola ma mi sento un po' stanca. È normale?	t	2025-12-14 10:00:00
26	2	9	Sì, i beta-bloccanti possono dare un po' di astenia iniziale. Il corpo si abituerà in qualche giorno.	t	2025-12-14 12:20:00
27	9	2	Tutto bene Dottore, il cuore è tranquillo ora. Ci vediamo il 30 per il rinnovo della ricetta.	f	2026-01-14 08:23:50.689165
28	7	2	Buonasera Dottore, è un periodo molto stressante al lavoro e sento spesso il cuore in gola. Posso fare un controllo?	t	2025-12-10 18:00:00
29	2	7	Certamente Giulia, lo stress gioca brutti scherzi. Vediamoci il 15 così ti tranquillizzi.	t	2025-12-10 19:30:00
30	7	2	Il magnesio va preso a stomaco pieno o vuoto?	t	2025-12-16 09:00:00
31	2	7	Meglio la sera lontano dai pasti, aiuta anche a riposare meglio.	t	2025-12-16 10:15:00
32	7	2	Dottore sto benissimo! Ci vediamo comunque a fine mese per chiudere il controllo?	f	2026-01-14 07:25:59.064003
33	6	4	Dottore, mi sono fatto male a calcetto ieri sera, il ginocchio è un pallone.	t	2025-12-02 08:30:00
34	4	6	Metti subito ghiaccio e vieni il 4 che lo controlliamo.	t	2025-12-02 09:15:00
35	8	4	Dottore sono rimasto bloccato con la schiena mentre sollevavo uno scatolone.	t	2025-12-05 14:00:00
36	4	8	Non forzare. Passa domani che ti sblocco.	t	2025-12-05 14:30:00
37	9	4	Dottore il bendaggio mi stringe un po', è normale?	t	2025-12-10 18:00:00
38	4	9	Sì, tienilo sollevato. Se le dita diventano blu vieni subito, altrimenti resisti.	t	2025-12-10 19:00:00
39	10	4	Dottore, la spalla scrocchia quando alzo il braccio, ma fa meno male.	f	2026-01-10 10:00:00
40	6	4	Dottore buongiorno, quando pensa di caricare il referto della visita di sabato? Mi serve per l'assicurazione.	f	2026-01-14 08:38:46.487764
41	9	4	Dottore, attendo il referto per iniziare la terapia. Grazie!	f	2026-01-14 11:08:46.487764
\.


--
-- TOC entry 3882 (class 0 OID 16692)
-- Dependencies: 222
-- Data for Name: metriche_salute; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.metriche_salute (id, paziente_id, medico_id, tipo, valore, unita_misura, data_misurazione) FROM stdin;
1	8	2	PRESSIONE_MAX	135.00	mmHg	2025-12-25
2	8	2	PRESSIONE_MIN	85.00	mmHg	2025-12-25
3	8	2	PESO	82.50	kg	2025-12-25
4	8	2	PRESSIONE_MAX	120.00	mmHg	2026-01-04
5	8	2	PRESSIONE_MIN	80.00	mmHg	2026-01-04
6	8	2	PESO	82.00	kg	2026-01-04
7	7	3	PESO	55.00	kg	2025-11-14
8	7	3	PESO	54.50	kg	2025-12-14
9	10	2	PRESSIONE_MAX	160.00	mmHg	2025-12-05
10	10	2	PRESSIONE_MIN	100.00	mmHg	2025-12-05
11	10	2	PRESSIONE_MAX	145.00	mmHg	2025-12-20
12	10	2	PRESSIONE_MIN	95.00	mmHg	2025-12-20
13	9	2	PRESSIONE_MAX	125.00	mmHg	2025-12-12
14	9	2	PRESSIONE_MIN	80.00	mmHg	2025-12-12
15	9	2	PRESSIONE_MAX	115.00	mmHg	2025-12-28
16	9	2	PRESSIONE_MIN	75.00	mmHg	2025-12-28
17	7	2	PRESSIONE_MAX	135.00	mmHg	2025-12-15
18	7	2	PRESSIONE_MIN	85.00	mmHg	2025-12-15
19	7	2	PRESSIONE_MAX	120.00	mmHg	2025-12-29
20	7	2	PRESSIONE_MIN	78.00	mmHg	2025-12-29
21	6	4	PESO	80.50	kg	2025-12-04
22	6	4	PESO	80.00	kg	2025-12-18
23	8	4	PESO	85.00	kg	2025-12-06
24	9	4	PESO	58.00	kg	2025-12-09
25	10	4	PESO	88.00	kg	2025-12-11
\.


--
-- TOC entry 3876 (class 0 OID 16627)
-- Dependencies: 216
-- Data for Name: prenotazioni; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.prenotazioni (id, paziente_id, medico_id, data_visita, stato, motivo) FROM stdin;
1	6	2	2026-01-30 18:00:00	CONFERMATA	Prima Visita
2	6	2	2026-02-20 19:00:00	RICHIESTA	Visione Esami
4	7	2	2026-01-30 18:00:00	RICHIESTA	Prima Visita
13	6	2	2025-11-14 10:39:07.733418	COMPLETATA	Prima Visita
14	8	2	2025-12-25 10:43:41.558108	COMPLETATA	Visione Esami
15	8	2	2026-01-04 10:48:37.94806	COMPLETATA	Visita di Controllo
16	8	2	2026-01-19 16:00:00	CONFERMATA	Consulto
17	7	3	2025-11-14 11:03:53.823278	COMPLETATA	Prima Visita
18	7	3	2025-12-14 11:03:53.823278	COMPLETATA	Visita di Controllo
19	7	3	2026-01-19 10:30:00	CONFERMATA	Visita di Controllo
21	9	3	2026-01-26 16:30:00	RICHIESTA	Consulto
22	6	2	2026-01-13 15:00:00	COMPLETATA	Visita di Controllo
23	10	2	2025-12-05 10:00:00	COMPLETATA	Prima Visita
24	10	2	2025-12-20 16:30:00	COMPLETATA	Visita di Controllo
25	10	2	2026-01-29 09:00:00	CONFERMATA	Visita di Controllo
26	9	2	2025-12-12 11:30:00	COMPLETATA	Prima Visita
27	9	2	2025-12-28 09:15:00	COMPLETATA	Visita di Controllo
28	9	2	2026-01-30 16:00:00	CONFERMATA	Visita di Controllo
29	7	2	2025-12-15 16:00:00	COMPLETATA	Prima Visita
30	7	2	2025-12-29 10:30:00	COMPLETATA	Visita di Controllo
31	7	2	2026-01-27 15:00:00	CONFERMATA	Visita di Controllo
32	6	4	2025-12-04 09:00:00	COMPLETATA	Prima Visita
33	6	4	2025-12-18 15:30:00	COMPLETATA	Visita di Controllo
34	6	4	2026-01-23 10:00:00	CONFERMATA	Visita di Controllo
35	8	4	2025-12-06 11:00:00	COMPLETATA	Prima Visita
36	8	4	2025-12-22 17:00:00	COMPLETATA	Visita di Controllo
37	8	4	2026-01-28 16:30:00	CONFERMATA	Visione Esami
38	9	4	2025-12-09 10:30:00	COMPLETATA	Prima Visita
39	9	4	2025-12-27 09:30:00	COMPLETATA	Visita di Controllo
40	9	4	2026-01-25 11:00:00	CONFERMATA	Visita di Controllo
41	10	4	2025-12-11 16:00:00	COMPLETATA	Consulto
42	10	4	2025-12-30 11:30:00	COMPLETATA	Visione Esami
43	10	4	2026-01-31 10:00:00	CONFERMATA	Visita di Controllo
44	6	4	2026-01-10 10:00:00	COMPLETATA	Visita di Controllo
45	9	4	2026-01-12 16:30:00	COMPLETATA	Consulto
20	6	3	2026-01-22 11:00:00	CONFERMATA	Prima Visita
\.


--
-- TOC entry 3880 (class 0 OID 16670)
-- Dependencies: 220
-- Data for Name: prescrizioni; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.prescrizioni (id, visita_id, nome_farmaco, dosaggio, data_emissione, data_fine) FROM stdin;
3	17	Ramipril	5mg - 1 compressa al mattino	2025-11-14	2025-12-14
4	19	Bisoprololo	1.25mg - 1 compressa al mattino	2026-01-04	2026-02-03
5	21	Epiduo Gel	Applicare la sera uno strato sottile	2025-11-14	2025-12-14
6	22	Epiduo Gel	Applicare a sere alterne	2025-12-14	2026-02-14
7	22	Cetaphil Crema Idratante	Applicare mattina e sera in abbondanza	2025-12-14	2026-02-14
8	24	Olmesartan	10mg - 1 compressa al mattino	2025-12-05	2025-12-20
9	25	Olmesartan	20mg - 1 compressa al mattino	2025-12-20	2026-02-20
10	26	Bisoprololo	1.25mg - 1 compressa al mattino	2025-12-12	2025-12-28
11	27	Bisoprololo	1.25mg - 1 compressa al mattino	2025-12-28	2026-02-28
12	28	Magnesio Supremo	1 cucchiaino in acqua tiepida la sera	2025-12-15	2026-01-15
13	29	Biancospino Gocce	20 gocce al bisogno in caso di agitazione	2025-12-29	2026-03-29
14	30	Oki Bustine	1 bustina dopo i pasti per 5 giorni	2025-12-04	2025-12-09
15	31	Condroprotector Plus	1 compressa al giorno per rinforzo cartilagine	2025-12-18	2026-02-18
16	32	Muscoril + Voltaren	1 iniezione al giorno per 5 giorni	2025-12-06	2025-12-11
17	34	Fastum Gel	Applicare 3 volte al dì	2025-12-09	2025-12-20
18	36	Cerotti Dicloreum	1 cerotto ogni 24h per 7 giorni	2025-12-11	2025-12-18
\.


--
-- TOC entry 3872 (class 0 OID 16571)
-- Dependencies: 212
-- Data for Name: specializzazioni; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.specializzazioni (id, nome) FROM stdin;
1	Cardiologia
2	Dermatologia
3	Medicina Generale
4	Ortopedia
5	Pediatria
6	Neurologia
7	Ginecologia
8	Oculistica
9	Psichiatria
10	Oncologia
11	Urologia
12	Endocrinologia
13	Gastroenterologia
14	Otorinolaringoiatria
15	Pneumologia
16	Reumatologia
17	Chirurgia Generale
18	Geriatria
19	Ematologia
\.


--
-- TOC entry 3870 (class 0 OID 16560)
-- Dependencies: 210
-- Data for Name: utenti; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.utenti (id, email, password, nome, cognome, telefono, data_nascita, ruolo, created_at, sesso) FROM stdin;
1	admin@healthconnect.com	$2a$12$CIAHVAoriYR7mjVyqwJ/ieb0egFrpZyLa49HEPJawGdUA30hhEwHy	Matteo	Tocci	1234567890	2004-12-22	ADMIN	2026-01-12 23:45:14.231454	M
2	mario.rossi@medico.it	$2a$10$UwW2C13Kxw8DmofgjPCThO3jZuXyjC.1xZzetwWta9bdz2XDjXfsC	Mario	Rossi	3331112222	1970-05-20	MEDICO	2026-01-13 00:57:39.138646	M
3	laura.verdi@medico.it	$2a$10$aZlrZ7lWr76b04BxXQ7m0.XWNUQmniKkNb3oc67UFBWRJ3bDDKGKm	Laura	Verdi	3334445555	1982-11-15	MEDICO	2026-01-13 00:59:26.934528	F
4	marco.neri@medico.it	$2a$10$D3oedHQIAOkliKS2hH9hT.8JUOiUfsEdJ4nbrPGm4jauLp0ff5qEC	Marco	Neri	3335558888	1978-08-30	MEDICO	2026-01-13 01:01:00.804751	M
5	giovanni.blu@medico.it	$2a$10$vjfamJFLxZ7tGXne/aSDeOCnsG6.ekTfyOMghx2fOj3oqRl0MtREK	Giovanni	Blu	3332223333	1982-12-12	MEDICO	2026-01-13 01:05:08.420612	M
6	luca.bianchi@paziente.it	$2a$10$o.O4YTZrDKjemttLEnak6.YROIDmWHfXK17.V9ue/g7va5nCQ1p96	Luca	Bianchi	3336667777	1990-03-10	PAZIENTE	2026-01-13 01:07:22.708673	M
7	giulia.neri@paziente.it	$2a$10$xAQfyiB6PIZDB75R0LbJd.2tCmqFmmJDTeMGPZ/L5qjNd.THvLaB.	Giulia	Neri	3338889999	1995-07-25	PAZIENTE	2026-01-13 01:08:05.134485	F
8	roberto.gialli@paziente.it	$2a$10$46AB6TsepFueHDvbgfUq5eGmXTau2HuCV5Z69qChokPXso60anP9K	Roberto	Gialli	3330001111	1985-01-12	PAZIENTE	2026-01-13 01:09:25.005592	M
9	anna.blu@paziente.it	$2a$10$wtiFL6BzKGOc2ztLlyDOqeJaBj.Apvni7AHvJZYL8WRen7FWDVMby	Anna	Blu	3332224444	1992-04-19	PAZIENTE	2026-01-13 01:10:27.283297	F
10	paolo.viola@paziente.it	$2a$10$js6QeGwuzM/nasvkSEUT4e/q6vAcPAzq57Kf3cFR80XBEceTvlwi6	Paolo	Viola	3339990000	1987-09-09	PAZIENTE	2026-01-13 01:11:21.7166	M
\.


--
-- TOC entry 3878 (class 0 OID 16646)
-- Dependencies: 218
-- Data for Name: visite; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.visite (id, prenotazione_id, paziente_id, medico_id, diagnosi, note_medico, data_visita) FROM stdin;
1	1	6	2	\N	\N	2026-01-30 18:00:00
17	13	6	2	Ipertensione arteriosa lieve	Rilevata pressione 140/90. Si consiglia dieta iposodica e monitoraggio.	2025-11-14 10:39:07.733418
18	14	8	2	Aritmia benigna	Esami del sangue e ECG nella norma. Extrasistoli dovute a stress.	2025-12-25 10:43:41.558108
19	15	8	2	Miglioramento sintomatologia	Pressione normalizzata e battito regolare. Lo stress sembra ridotto.	2026-01-04 10:48:37.94806
20	16	8	2	\N	\N	2026-01-19 16:00:00
21	17	7	3	Acne papulo-pustolosa severa	Paziente presenta infiammazione diffusa sul volto. Si inizia terapia topica combinata. Rivedere tra 1 mese.	2025-11-14 11:03:53.823278
22	18	7	3	Miglioramento iniziale acne	Riduzione dell'infiammazione del 30%. La paziente lamenta secchezza cutanea. Aggiustamento terapia.	2025-12-14 11:03:53.823278
23	22	6	2	\N	\N	2026-01-13 15:00:00
24	23	10	2	Ipertensione arteriosa moderata	Paziente riferisce cefalea mattutina ricorrente. Valori pressori elevati. Si consiglia diario pressorio e inizio terapia.	2025-12-05 10:00:00
25	24	10	2	Risposta parziale alla terapia	La pressione è scesa ma la minima resta alta. Aumentato dosaggio farmaco. Paziente riferisce meno mal di testa.	2025-12-20 16:30:00
26	26	9	2	Tachicardia sinusale inappropriata	Paziente riferisce cardiopalmo frequente anche a riposo. ECG conferma tachicardia a 115 bpm. Pressione nella norma.	2025-12-12 11:30:00
27	27	9	2	Buona risposta ai beta-bloccanti	Frequenza cardiaca a riposo scesa a 72 bpm. La paziente riferisce netto miglioramento della sintomatologia.	2025-12-28 09:15:00
28	29	7	2	Palpitazioni da stress	La paziente riferisce episodi sporadici di batticuore. ECG negativo per patologie maggiori. Pressione leggermente mossa.	2025-12-15 16:00:00
29	30	7	2	Sintomatologia in remissione	Il riposo e l'integrazione di magnesio hanno ridotto gli episodi. Parametri vitali ottimali.	2025-12-29 10:30:00
30	32	6	4	Trauma distorsivo ginocchio dx	Ginocchio gonfio e dolente. Sospetta lesione meniscale. Riposo, ghiaccio e risonanza magnetica.	2025-12-04 09:00:00
31	33	6	4	Lesione menisco mediale	RM conferma lesione. Il gonfiore è diminuito. Si prosegue con fisioterapia conservativa prima di valutare intervento.	2025-12-18 15:30:00
32	35	8	4	Lombalgia acuta	Contrattura muscolare paravertebrale. Paziente bloccato. Si consiglia riposo e terapia iniettiva.	2025-12-06 11:00:00
33	36	8	4	Miglioramento mobilità	Dolore ridotto. Persiste rigidità mattutina. Iniziare ginnastica posturale.	2025-12-22 17:00:00
34	38	9	4	Distorsione caviglia sx di II grado	Edema importante. Nessuna frattura alla radiografia. Applicato bendaggio funzionale.	2025-12-09 10:30:00
35	39	9	4	Rimozione bendaggio	La caviglia è stabile. Lieve gonfiore residuo. Può iniziare il carico progressivo.	2025-12-27 09:30:00
36	41	10	4	Tendinite sovraspinato	Dolore nei movimenti overhead. Test di Neer positivo. Sospendere palestra per 15 giorni.	2025-12-11 16:00:00
37	42	10	4	Controllo ecografia spalla	Ecografia conferma infiammazione ma nessuna lesione completa. Si consigliano infiltrazioni se il dolore persiste.	2025-12-30 11:30:00
38	2	6	2	\N	\N	2026-02-20 19:00:00
40	4	7	2	\N	\N	2026-01-30 18:00:00
41	19	7	3	\N	\N	2026-01-19 10:30:00
42	20	6	3	\N	\N	2026-01-22 11:00:00
43	21	9	3	\N	\N	2026-01-26 16:30:00
44	25	10	2	\N	\N	2026-01-29 09:00:00
45	28	9	2	\N	\N	2026-01-30 16:00:00
46	31	7	2	\N	\N	2026-01-27 15:00:00
47	34	6	4	\N	\N	2026-01-23 10:00:00
48	37	8	4	\N	\N	2026-01-28 16:30:00
49	40	9	4	\N	\N	2026-01-25 11:00:00
50	43	10	4	\N	\N	2026-01-31 10:00:00
51	44	6	4	\N	\N	2026-01-10 10:00:00
52	45	9	4	\N	\N	2026-01-12 16:30:00
\.


--
-- TOC entry 3891 (class 0 OID 0)
-- Dependencies: 213
-- Name: dettagli_medici_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.dettagli_medici_id_seq', 4, true);


--
-- TOC entry 3892 (class 0 OID 0)
-- Dependencies: 223
-- Name: messaggi_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.messaggi_id_seq', 41, true);


--
-- TOC entry 3893 (class 0 OID 0)
-- Dependencies: 221
-- Name: metriche_salute_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.metriche_salute_id_seq', 25, true);


--
-- TOC entry 3894 (class 0 OID 0)
-- Dependencies: 215
-- Name: prenotazioni_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.prenotazioni_id_seq', 45, true);


--
-- TOC entry 3895 (class 0 OID 0)
-- Dependencies: 219
-- Name: prescrizioni_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.prescrizioni_id_seq', 18, true);


--
-- TOC entry 3896 (class 0 OID 0)
-- Dependencies: 211
-- Name: specializzazioni_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.specializzazioni_id_seq', 19, true);


--
-- TOC entry 3897 (class 0 OID 0)
-- Dependencies: 209
-- Name: utenti_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.utenti_id_seq', 10, true);


--
-- TOC entry 3898 (class 0 OID 0)
-- Dependencies: 217
-- Name: visite_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.visite_id_seq', 52, true);


--
-- TOC entry 3704 (class 2606 OID 16586)
-- Name: dettagli_medici dettagli_medici_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.dettagli_medici
    ADD CONSTRAINT dettagli_medici_pkey PRIMARY KEY (id);


--
-- TOC entry 3716 (class 2606 OID 16762)
-- Name: impostazioni_notifiche impostazioni_notifiche_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.impostazioni_notifiche
    ADD CONSTRAINT impostazioni_notifiche_pkey PRIMARY KEY (utente_id);


--
-- TOC entry 3714 (class 2606 OID 16737)
-- Name: messaggi messaggi_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.messaggi
    ADD CONSTRAINT messaggi_pkey PRIMARY KEY (id);


--
-- TOC entry 3712 (class 2606 OID 16697)
-- Name: metriche_salute metriche_salute_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.metriche_salute
    ADD CONSTRAINT metriche_salute_pkey PRIMARY KEY (id);


--
-- TOC entry 3706 (class 2606 OID 16634)
-- Name: prenotazioni prenotazioni_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.prenotazioni
    ADD CONSTRAINT prenotazioni_pkey PRIMARY KEY (id);


--
-- TOC entry 3710 (class 2606 OID 16675)
-- Name: prescrizioni prescrizioni_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.prescrizioni
    ADD CONSTRAINT prescrizioni_pkey PRIMARY KEY (id);


--
-- TOC entry 3700 (class 2606 OID 16577)
-- Name: specializzazioni specializzazioni_nome_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.specializzazioni
    ADD CONSTRAINT specializzazioni_nome_key UNIQUE (nome);


--
-- TOC entry 3702 (class 2606 OID 16575)
-- Name: specializzazioni specializzazioni_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.specializzazioni
    ADD CONSTRAINT specializzazioni_pkey PRIMARY KEY (id);


--
-- TOC entry 3696 (class 2606 OID 16569)
-- Name: utenti utenti_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.utenti
    ADD CONSTRAINT utenti_email_key UNIQUE (email);


--
-- TOC entry 3698 (class 2606 OID 16567)
-- Name: utenti utenti_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.utenti
    ADD CONSTRAINT utenti_pkey PRIMARY KEY (id);


--
-- TOC entry 3708 (class 2606 OID 16653)
-- Name: visite visite_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.visite
    ADD CONSTRAINT visite_pkey PRIMARY KEY (id);


--
-- TOC entry 3718 (class 2606 OID 16592)
-- Name: dettagli_medici fk_medico_spec; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.dettagli_medici
    ADD CONSTRAINT fk_medico_spec FOREIGN KEY (specializzazione_id) REFERENCES public.specializzazioni(id);


--
-- TOC entry 3717 (class 2606 OID 16587)
-- Name: dettagli_medici fk_medico_utente; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.dettagli_medici
    ADD CONSTRAINT fk_medico_utente FOREIGN KEY (utente_id) REFERENCES public.utenti(id) ON DELETE CASCADE;


--
-- TOC entry 3726 (class 2606 OID 16703)
-- Name: metriche_salute fk_metrica_medico; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.metriche_salute
    ADD CONSTRAINT fk_metrica_medico FOREIGN KEY (medico_id) REFERENCES public.utenti(id);


--
-- TOC entry 3725 (class 2606 OID 16698)
-- Name: metriche_salute fk_metrica_paziente; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.metriche_salute
    ADD CONSTRAINT fk_metrica_paziente FOREIGN KEY (paziente_id) REFERENCES public.utenti(id);


--
-- TOC entry 3728 (class 2606 OID 16743)
-- Name: messaggi fk_msg_destinatario; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.messaggi
    ADD CONSTRAINT fk_msg_destinatario FOREIGN KEY (destinatario_id) REFERENCES public.utenti(id);


--
-- TOC entry 3727 (class 2606 OID 16738)
-- Name: messaggi fk_msg_mittente; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.messaggi
    ADD CONSTRAINT fk_msg_mittente FOREIGN KEY (mittente_id) REFERENCES public.utenti(id);


--
-- TOC entry 3720 (class 2606 OID 16640)
-- Name: prenotazioni fk_pren_medico; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.prenotazioni
    ADD CONSTRAINT fk_pren_medico FOREIGN KEY (medico_id) REFERENCES public.utenti(id);


--
-- TOC entry 3719 (class 2606 OID 16635)
-- Name: prenotazioni fk_pren_paziente; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.prenotazioni
    ADD CONSTRAINT fk_pren_paziente FOREIGN KEY (paziente_id) REFERENCES public.utenti(id);


--
-- TOC entry 3724 (class 2606 OID 16676)
-- Name: prescrizioni fk_presc_visita; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.prescrizioni
    ADD CONSTRAINT fk_presc_visita FOREIGN KEY (visita_id) REFERENCES public.visite(id) ON DELETE CASCADE;


--
-- TOC entry 3723 (class 2606 OID 16664)
-- Name: visite fk_visita_medico; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.visite
    ADD CONSTRAINT fk_visita_medico FOREIGN KEY (medico_id) REFERENCES public.utenti(id);


--
-- TOC entry 3722 (class 2606 OID 16659)
-- Name: visite fk_visita_paziente; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.visite
    ADD CONSTRAINT fk_visita_paziente FOREIGN KEY (paziente_id) REFERENCES public.utenti(id);


--
-- TOC entry 3721 (class 2606 OID 16654)
-- Name: visite fk_visita_pren; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.visite
    ADD CONSTRAINT fk_visita_pren FOREIGN KEY (prenotazione_id) REFERENCES public.prenotazioni(id);


--
-- TOC entry 3729 (class 2606 OID 16763)
-- Name: impostazioni_notifiche impostazioni_notifiche_utente_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.impostazioni_notifiche
    ADD CONSTRAINT impostazioni_notifiche_utente_id_fkey FOREIGN KEY (utente_id) REFERENCES public.utenti(id) ON DELETE CASCADE;


-- Completed on 2026-01-14 16:51:57 CET

--
-- PostgreSQL database dump complete
--

\unrestrict JyNIUjs4KnSW4PrsBbxeS4ryEZXGZOg837CsaqPt8F6dgLEx1VKCV6HlMaYuoTA

