spring.application.name=backend_healthconnect

# Server
server.port=8080

# Database MySQL
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=healthconnect
spring.datasource.driver-class-name=org.postgresql.Driver

# Infermedica
api.infermedica.url=https://api.infermedica.com/v3
api.infermedica.app-id=
api.infermedica.app-key=

# MyMemory
api.mymemory.url=https://api.mymemory.translated.net/get
api.mymemory.email=webproject.unical@gmail.com

app.simulation.mode=true

# Mail
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=webproject.unical@gmail.com
spring.mail.password=uuzf oans afjg rnzf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
